export const environment = {
  production: false,
  API_URL: 'https://scenta-holics.com/api/',
  // BASE_URL: 'https://scenta-holics.com/',
  // API_URL: 'https://scenta-holics.com//api',
  // BASE_URL: 'https://scenta-holics.com/',
  // API_URL: 'http://localhost:8200/api-tybo-accounting',
  BASE_URL: 'http://localhost:4200',
  BASE_URL_ADMIN: 'http://localhost:4200',
  ACCOUNT_TEST_EMAIL: 'info@scenta-holics.com',
  ACCOUNT_TEST_PASSWORD: 'info@scenta-holics.com',
  TEST_EMAIL_ACCOUNT: 'admin@tybo-services.co.za',
  DF_LOGO: `https://scenta-holics.com/api//api/upload/uploads/1625394631iio.jpg`,
  DF_USER_LOGO: `https://scenta-holics.com/api//api/upload/uploads/1625394631iio.jpg`,
};
